apiVersion: v1
kind: Service
metadata:
  name: Coffee-shop-service
spec:
  type: NodePort
  selector:
    app: coffee-shop
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080

